version: '3.8'

services:
  ui:
    container_name: diabetes-ui
    image: ${IMAGE_NAME}
    environment:
      PORT: $PORT
      NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL}
    build:
      context: .
    ports:
      - 127.0.0.1:1313:$PORT