on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repo
         uses: actions/checkout@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
         with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_SECRET }}

       - name: Build and push image
         run: |
           export IMAGE_NAME=${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
           docker compose -f docker-compose-build.yml build
           docker compose push

  server_update:
    needs: build_and_push
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose-prod.yml"
          target: /usr/diabetes-ui/

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Connect
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME
          script: |
            # Check if IMAGE_NAME is empty
            if [ -z "$IMAGE_NAME" ]; then
              echo "ERROR: IMAGE_NAME environment variable is empty"
              exit 1
            fi
            
            export IMAGE_NAME=$IMAGE_NAME

            echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            
            cd /usr/diabetes-ui/
            > .env
            echo "NUXT_APP_MODEL_URL=${{ secrets.NUXT_APP_MODEL_URL }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            
            echo "Removing image existing container"
            docker compose rm -fs

            echo "Pullin an image"
            docker compose pull

            echo "Running an image"
            docker compose -f docker-compose-prod.yml up -d